# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: ''

menu:
- {name: 'home', path: '', url: 'index.html'}
- {name: 'about', path: 'menu', url: 'about.html'}
- {name: 'contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/kelseyball'}
# - {icon: 'twitter', link: ''}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kelsey-ball-b573b0a7/'}
- {icon: 'envelope', link: 'mailto:kelseytaylorball@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
# pagination:
#  next_page: 'Newer'
#  previous_page: 'Older'

sharing_button_prompt: 'feel free to share!'

related_posts: 'you may also enjoy:'

post_date_prefix: 'written on'
